### ISSUE TITLE
Hello, everyone there?

### ISSUE THREAD

**Issue by heipiao233** [CloudLoaderMC/CloudLoader#1]
### **_I can't use Discord due to our government's limit._**
I'm glad to hear that. I want to ask some questions.
1. Can I use Forge and Fabric mods together with this loader quite now?
2. Is this loader based on Forge, Fabric or others? I think it's Forge.

**Comment by DevReaper0** [comment]
For your first question, as of right now, the loader has some issues with mixins causing most Fabric mods to not work and not crashing Cloud. After the issue is resolved, it *might* work, but I'll have to see.

And for the second, you are correct in that it *is* internally based on Forge, and there's still quite a few files (like README.md) that need to be updated for Cloud.

**Comment by heipiao233** [comment]
I have a project: [pillow](https://github.com/PillowMC/pillow). It have a similar goal with yours: compatibility between Forge and Quilt. But it doesn't provide compatibility between Forge and Bukkit. It also has some issues: Forge patches confident with Quilt mixins. This causes It doesn't compat with Quilted Fabric API. As you seen, it is a serious problem. I'm planning to re-implement FAPI and QSL.
